In [1]:
# 文字列'123'を整数の123に変換する
int('123')

123

In [2]:
# 文字列'123.4'を少数の123.4に変換する
float('123.4')

123.4

In [3]:
# 文字列'hello'から前後の空白をすべて取り除いてください。
'   hello       　'.strip()

'hello'

In [4]:
# [[1,2,3],[4,5,6]]はリストにリストが入っています。内側のリストの最大値
# をそれぞれ求めるプログラムを書いてください。
a = [[1,2,3],[4,5,6]]

for i in a:
    max_value = i[0]
    for j in i:
        if(j > max_value):
            max_value = j
    print(max_value)

3
6


In [5]:
a = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
for i in a:
    print('loop1: ' + str(i))
    for j in i:
        print('loop2: ' + str(j))

loop1: [1, 2, 3]
loop2: 1
loop2: 2
loop2: 3
loop1: [4, 5, 6]
loop2: 4
loop2: 5
loop2: 6
loop1: [7, 8, 9]
loop2: 7
loop2: 8
loop2: 9


In [7]:
a[1:]

[[4, 5, 6], [7, 8, 9]]

In [8]:
len(a)

3

In [9]:
len(a[1])

3

In [10]:
a[0][2]=10

In [11]:
a

[[1, 2, 10], [4, 5, 6], [7, 8, 9]]

In [12]:
a.pop()

[7, 8, 9]

In [13]:
a

[[1, 2, 10], [4, 5, 6]]

In [14]:
a.append([20,30,40])

In [15]:
a

[[1, 2, 10], [4, 5, 6], [20, 30, 40]]

In [16]:
a.pop()

[20, 30, 40]

In [17]:
a.pop

<function list.pop(index=-1, /)>

In [18]:
a.pop()

[4, 5, 6]

In [19]:
a

[[1, 2, 10]]

In [20]:
import pandas as pd
pd.DataFrame([[1, "abc"],[2,"def"]], columns=("id", "name"))

id name
0   1  abc
1   2  def

In [21]:
data = {'Language': ['Python', 'C++', 'Java'], # 文字列
        'Year': [1991, 1983, 1995], # 数値
        'Static': [False, True, True]} # 真偽値
df = pd.DataFrame(data)

print(df)

  Language  Year  Static
0   Python  1991   False
1      C++  1983    True
2     Java  1995    True


In [22]:
df = pd.DataFrame(data, index = ['one', 'two', 'three']) # インデックスを指定

print(df)

      Language  Year  Static
one     Python  1991   False
two        C++  1983    True
three     Java  1995    True


In [23]:
df = pd.DataFrame(data, index = ['one', 'two', 'three'], columns = ['Language', 'Static', 'Year']) # columns

print(df)

      Language  Static  Year
one     Python   False  1991
two        C++    True  1983
three     Java    True  1995


In [24]:
print(df.loc[['two']]) # 'two'行を抽出

    Language  Static  Year
two      C++    True  1983


In [25]:
print(df.loc[:, 'Year']) # 'Year'列を抽出

one      1991
two      1983
three    1995
Name: Year, dtype: int64


In [26]:
print(df.loc['one', 'Language']) # 'one'行、 'Language'列を抽出

Python


In [27]:
print(df.iloc[:,1]) # 1列目を抽出

one      False
two       True
three     True
Name: Static, dtype: bool


In [28]:
print(df.iloc[[1]]) # 1行目を抽出

    Language  Static  Year
two      C++    True  1983


In [29]:
print(df.iloc[1, 2]) # 1行2列目抽出

1983


In [30]:
print(type(df.iloc[[1]]))

<class 'pandas.core.frame.DataFrame'>


In [31]:
print(type(df.iloc[1]))

<class 'pandas.core.series.Series'>


In [32]:
l = ['Alice', 'Bob', 'Charlie']

for name in l:
    print(name)

Alice
Bob
Charlie


In [33]:
for name in l:
    if name == 'Bob':
        print('!!BREAK!!')
        break
    print(name)

Alice
!!BREAK!!


In [34]:
for name in l:
    if name == 'Bob':
        print('!!SKIP!!')
        continue
    print(name)

Alice
!!SKIP!!
Charlie


In [35]:
for name in l:
    print(name)
else:
    print('!!FINISH!!')

Alice
Bob
Charlie
!!FINISH!!


In [36]:
for name in l:
    if name == 'Bob':
        print('!!BREAK!!')
        break
    print(name)
else:
    print('!!FINISH!!')

Alice
!!BREAK!!


In [37]:
for name in l:
    if name == 'Bob':
        print('!!SKIP!!')
        continue
    print(name)
else:
    print('!!FINISH!!')

Alice
!!SKIP!!
Charlie
!!FINISH!!


In [38]:
for i in range(3):
    print(i)

0
1
2


In [39]:
print(list(range(3, 10, 2)))

[3, 5, 7, 9]


In [40]:
print(list(range(10,3,2)))

[]


In [41]:
print(list(range(10, 3, -2)))

[10, 8, 6, 4]


In [42]:
print(list(range(3, 10, -2)))

[]


In [43]:
print(range(3))

range(0, 3)


In [44]:
print(range(2,3))

range(2, 3)


In [45]:
print(list(range(1,3)))

[1, 2]


In [46]:
print(list(range(10, 2, -2)))

[10, 8, 6, 4]


In [47]:
print(range(0, 3) == range(3))

True


In [48]:
print(range(3, 10, 1) == range(3, 10))

True


In [49]:
print(range(0, 10, 1) == range(0, 10) == range(10))

True


In [50]:
print(list(reversed(range(3, 10, 2))))

[9, 7, 5, 3]


In [51]:
for i in reversed(range(3, 10, 2)):
    print(i)

9
7
5
3


In [52]:
print([i / 10 for i in range(3, 10, 2)])

[0.3, 0.5, 0.7, 0.9]


In [53]:
print([i * 0.1 for i in range(3, 10, 2)])

[0.30000000000000004, 0.5, 0.7000000000000001, 0.9]


In [54]:
print([round(i * 0.1, 1) for i in range(3, 10, 2)])

[0.3, 0.5, 0.7, 0.9]


In [55]:
import numpy as np

In [56]:
print(np.arange(3))

[0 1 2]


In [57]:
print(np.arange(3, 10))

[3 4 5 6 7 8 9]


In [58]:
print(np.arange(3, 10, 2))

[3 5 7 9]


In [59]:
print(np.arange(0.3, 1.0, 0.2))

[0.3 0.5 0.7 0.9]


In [60]:
print(range(3))

range(0, 3)


In [61]:
print(type(range(3)))

<class 'range'>


In [62]:
print(l)

['Alice', 'Bob', 'Charlie']


In [63]:
for name in l:
    print(name)

Alice
Bob
Charlie


In [64]:
for i, name in enumerate(l):
    print(i, name)

0 Alice
1 Bob
2 Charlie


In [65]:
for i ,name in enumerate(l, 1):
    print(i, name)

1 Alice
2 Bob
3 Charlie


In [66]:
for i, name in enumerate(l, 42):
    print(i, name)

42 Alice
43 Bob
44 Charlie


In [67]:
l

['Alice', 'Bob', 'Charlie']

In [68]:
for i, name in enumerate(l, 1):
    print('{:03}_{}'.format(i, name))

001_Alice
002_Bob
003_Charlie


In [69]:
for i, name in enumerate(l):
    print(i * 3, name)

0 Alice
3 Bob
6 Charlie


In [70]:
names = ['Alice', 'Bob', 'Charlie']
ages = [24, 50, 18]

In [71]:
for name, age in zip(names, ages):
    print(name, age)

Alice 24
Bob 50
Charlie 18


In [72]:
points = [100, 85, 90]

In [73]:
for name, age, point in zip(names, ages, points):
    print(name, age, point)

Alice 24 100
Bob 50 85
Charlie 18 90


In [74]:
import os

In [75]:
os.listdir()

['.ipynb_checkpoints',
 'Nintendo.csv',
 'Python演習.ipynb',
 'SHARP.csv',
 'Sony.csv',
 'Toshiba.csv',
 'yobareru.py',
 'yobu.py',
 '__pycache__']

In [76]:
import yobareru

モジュール名：yobareru


In [77]:
import yobu

Hello World!


In [78]:
for i, (name, age) in enumerate(zip(names, ages)):
    print(i, name, age)

0 Alice 24
1 Bob 50
2 Charlie 18


In [79]:
for i in reversed(range(3)):
    print(i)

2
1
0


In [80]:
for i in range(2, -1, -1):
    print(i)

2
1
0


In [81]:
for i, name in reversed(list(enumerate(l))):
    print(i, name)

2 Charlie
1 Bob
0 Alice


In [82]:
for i, name in enumerate(reversed(l)):
    print(i, name)

0 Charlie
1 Bob
2 Alice


In [83]:
age

18

In [84]:
ages

[24, 50, 18]

In [85]:
for name, age in reversed(list(zip(l, ages))):
    print(name, age)

Charlie 18
Bob 50
Alice 24


In [86]:
zip(l)

In [87]:
zip(l, ages)

In [88]:
list(zip(l, ages))

[('Alice', 24), ('Bob', 50), ('Charlie', 18)]

In [89]:
l1 = [1, 2, 3]
l2 = [10, 20, 30]

In [90]:
for i in l1:
    for j in l2:
        print(i, j)

1 10
1 20
1 30
2 10
2 20
2 30
3 10
3 20
3 30


In [91]:
import itertools

In [92]:
for i, j in itertools.product(l1, l2):
    print(i, j)

1 10
1 20
1 30
2 10
2 20
2 30
3 10
3 20
3 30


In [93]:
d = {'key1': 1, 'key2': 2, 'key3': 3}

In [94]:
for k in d:
    print(k)

key1
key2
key3


In [95]:
print(k)

key3


In [96]:
print(d)

{'key1': 1, 'key2': 2, 'key3': 3}


In [97]:
print('key1')

key1


In [98]:
print(d['key1'])

1


In [99]:
print(d[1])

KeyError: 1

In [100]:
for v in d.values():
    print(v)

1
2
3


In [101]:
for k, v in d.items():
    print(k, v)

key1 1
key2 2
key3 3


In [102]:
squares = [i**2 for i in range(5)]

In [103]:
print(squares)

[0, 1, 4, 9, 16]
